<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <link href="../../bootstrap-4-4-1/css/bootstrap.css" rel="stylesheet" type="text/css"/>
    <link href="../../css/w3.css" rel="stylesheet" type="text/css"/>
    ,
    <link href="css/css.css" rel="stylesheet" type="text/css"/>
    <script src="../../js/jquery-3.5.1.min.js" type="text/javascript">
    </script>
    <title>
      Document
    </title>
  </head>
  <body>
    <h1>
      1-Bases-de-datos-en-la-vida-cotidiana
    </h1>
    <div class="container cuerpo">
      <div class="row">
        <div class="col-6">
          <table style="width:100%">
            <tr>
              <th>
                stuld
              </th>
              <th>
                lastName
              </th>
              <th>
                firstName
              </th>
              <th>
                major
              </th>
              <th>
                credits
              </th>
            </tr>
            <tr>
              <td>
                Jill
              </td>
              <td>
                Smith
              </td>
              <td>
                Jill
              </td>
              <td>
                Smith
              </td>
              <td>
                50
              </td>
            </tr>
            <tr>
              <td>
                Eve
              </td>
              <td>
                Jackson
              </td>
              <td>
                94
              </td>
            </tr>
          </table>
        </div>
        <div class="col-6">
          <table style="width:100%">
            <tr>
              <th>
                fac ld
              </th>
              <th>
                name
              </th>
              <th>
                department
              </th>
              <th>
                rank
              </th>
            </tr>
            <tr>
              <td>
                Jill
              </td>
              <td>
                Smith
              </td>
              <td>
                50
              </td>
            </tr>
            <tr>
              <td>
                Eve
              </td>
              <td>
                Jackson
              </td>
              <td>
                94
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
    <!--     <table style="width:100%">
      <tr>
        <th>
          Firstname
        </th>
        <th>
          Lastname
        </th>
        <th>
          Age
        </th>
      </tr>
      <tr>
        <td>
          Jill
        </td>
        <td>
          Smith
        </td>
        <td>
          50
        </td>
      </tr>
      <tr>
        <td>
          Eve
        </td>
        <td>
          Jackson
        </td>
        <td>
          94
        </td>
      </tr>
    </table>
    <table style="width:100%">
      <tr>
        <th>
          Firstname
        </th>
        <th>
          Lastname
        </th>
        <th>
          Age
        </th>
      </tr>
      <tr>
        <td>
          Jill
        </td>
        <td>
          Smith
        </td>
        <td>
          50
        </td>
      </tr>
      <tr>
        <td>
          Eve
        </td>
        <td>
          Jackson
        </td>
        <td>
          94
        </td>
      </tr>
    </table>
    <table style="width:100%">
      <tr>
        <th>
          Firstname
        </th>
        <th>
          Lastname
        </th>
        <th>
          Age
        </th>
      </tr>
      <tr>
        <td>
          Jill
        </td>
        <td>
          Smith
        </td>
        <td>
          50
        </td>
      </tr>
      <tr>
        <td>
          Eve
        </td>
        <td>
          Jackson
        </td>
        <td>
          94
        </td>
      </tr>
    </table>
    <table style="width:100%">
      <tr>
        <th>
          Firstname
        </th>
        <th>
          Lastname
        </th>
        <th>
          Age
        </th>
      </tr>
      <tr>
        <td>
          Jill
        </td>
        <td>
          Smith
        </td>
        <td>
          50
        </td>
      </tr>
      <tr>
        <td>
          Eve
        </td>
        <td>
          Jackson
        </td>
        <td>
          94
        </td>
      </tr>
    </table>
    <table style="width:100%">
      <tr>
        <th>
          Firstname
        </th>
        <th>
          Lastname
        </th>
        <th>
          Age
        </th>
      </tr>
      <tr>
        <td>
          Jill
        </td>
        <td>
          Smith
        </td>
        <td>
          50
        </td>
      </tr>
      <tr>
        <td>
          Eve
        </td>
        <td>
          Jackson
        </td>
        <td>
          94
        </td>
      </tr>
    </table> -->
  </body>
</html>
